### ISSUE TITLE
anzahl asthaufen

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/erfolgskontrolle#20]
https://github.com/wieselundco/erfolgskontrolle/blob/eb5def47356ee4fea7d9f04fdad32adc9221cacb/04_Methode.Rmd#L77-L77<br/><br/>@wicoz: Warum sprichst du von 50 Asthaufen? es sind doch 39

**Comment by wicoz** [comment]
stimmt...
*************************
<http://www.wieselundco.ch/news>
www.wieselundco.ch


Stefan Keller, Projektleitung
Aeschstrasse 23 <https://wogeno-mogelsberg.clubdesk.com/>
9122 Mogelsberg <https://wogeno-mogelsberg.clubdesk.com/>
076 374 70 01
044 500 52 82


Am Do., 3. Juni 2021 um 23:36 Uhr schrieb Nils ***@***.***>:
