### ISSUE TITLE
10 parameter?

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/erfolgskontrolle#21]
https://github.com/wieselundco/erfolgskontrolle/blob/eb5def47356ee4fea7d9f04fdad32adc9221cacb/04_Methode.Rmd#L77-L77<br/><br/>@wicoz: ist alter auch ein parameter? den hast du aber gar nicht untersucht oder? sonst zähle ich nur 9

**Comment by wicoz** [comment]
Alter hab ich in der Datenbank abgerufen; gilt auch als Parameter.

*************************
<http://www.wieselundco.ch/news>
www.wieselundco.ch


Stefan Keller, Projektleitung
Aeschstrasse 23 <https://wogeno-mogelsberg.clubdesk.com/>
9122 Mogelsberg <https://wogeno-mogelsberg.clubdesk.com/>
076 374 70 01
044 500 52 82


Am Do., 3. Juni 2021 um 23:35 Uhr schrieb Nils ***@***.***>:

**Comment by ratnanil** [comment]
aktuell arbeite ich nur mit 9 parameter und habe das überall so beschrieben. Falls ich das alter noch mitberücksichtige, werde ich das enstprechend anpassen
