### ISSUE TITLE
Tabelle total Nachweise unter 5.2 layouten

### ISSUE THREAD

**Issue by wicoz** [wieselundco/erfolgskontrolle#23]
Tabelle "Total Nachweise der einzelnen Arten in Erhebung 1 (Asthaufen) und 2 (Winterquartiere):
Asthaufen  (Herm: 55;  Ilt: 2; Mw: 0) 
Winterquartiere (Herm: 4; Ilt: 3; Mw: 0)

**Comment by ratnanil** [comment]
https://forschung.wieselundco.ch/erfolgskontrolle/diskussion-und-fazit.html#nachweisquote-im-vergleich-mit-anderen-studien
