### ISSUE TITLE
Abbildung 5.8 layouten

### ISSUE THREAD

**Issue by wicoz** [wieselundco/erfolgskontrolle#24]
bei mir werden nur die grünen Hermelin Felder angezeigt - der Rest ist weiss

**Comment by ratnanil** [comment]
https://forschung.wieselundco.ch/erfolgskontrolle/resultate.html#erhebung-3-erhebung-von-asthaufen-eigenschaften-zur-ermittlung-attraktivit%C3%A4tsf%C3%B6rdernder-faktoren-1
