### ISSUE TITLE
anzahl asthaufen pro merkmalsausprägung in den methoden teil verschieben

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/erfolgskontrolle#25]
https://forschung.wieselundco.ch/erfolgskontrolle/resultate.html#erhebung-3-erhebung-von-asthaufen-eigenschaften-zur-ermittlung-attraktivit%C3%A4tsf%C3%B6rdernder-faktoren-1

**Comment by wicoz** [comment]
@ratnanil yep, die Bereinigung zwischen Methoden- und Resultateteil ist noch offen


gemäss Mail vom 28. Juli
geeignetes Bild für Resultate Teil
![D90_20140605](https://user-images.githubusercontent.com/49158554/127890554-e98f47f9-9b84-4285-9427-187dd3e708d8.jpg)

Auch den Text gilt es zu verifizieren, wohin er gehört, 
Es brauchr im Resultate Teil noch einen ausgedeutschten Abschnitt, dass der grobe Asthaufen attraktiver ist. 
Bitte um Bescheid, sobald nachgeführt.

**Comment by ratnanil** [comment]
>  geeignetes Bild für Resultate Teil

wohin soll das genau?

**Comment by wicoz** [comment]
Neu gibts ja unter Resultate 4.3 Abbildungen zur Statistik, darum würde ich das Bild unter 5.4 (am Schluss) einfügen. 
Beschriftung: 
Aus Erhebung 3 resultiert mit hoher Signifikanz, dass ein Nachweis von den Zielarten bei jenen Asthaufen wahrscheinlicher ist, die aus grobem Astmaterial aufgebaut sind.
