### ISSUE TITLE
shortlink korrigieren

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/erfolgskontrolle#26]
https://github.com/wieselundco/website/issues/13#issuecomment-913025092

**Comment by ratnanil** [comment]
> Hab mir notiert, dass wieselundco.ch/projekt/massnahmen in WK Bericht vorkommt.

wohin sollte das verlinken, @wicoz ?

**Comment by wicoz** [comment]
Du hast das bereits richtig antizipiert; auf https://wieselundco.ch/welche-massnahmen
