### ISSUE TITLE
Namenswechsel!!

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/erfolgskontrolle#27]
ACHTUNG!! Mit dem loslösen vom Metanet gibt es auch folgende Änderung: 

http://forschung.wieselundco.ch/erfolgskontrolle/ heisst jetzt neu http://erfolgskontrolle.wieselundco.ch/

**Comment by wicoz** [comment]
Wie erwähnt, im Schlussbericht ist die alte Adresse drin. 
Der Druckauftrag ist bereits erteilt. 
-> Ist eine Umleitung möglich?

Wenn nein: 
Wann wird die alte Adresse nicht mehr aktiv sein?

**Comment by ratnanil** [comment]
>  -> Ist eine Umleitung möglich?

ja ich werde das auf jeden Fall versuchen, ich denke das sollte klappen

**Comment by wicoz** [comment]
Danke - das wär wirklich wichtig, denn nicht nur im Schlussbericht, auch im einen Video, das ich aus verschiedenen Gründen nicht mehr aktualisieren möchte, wird der alte Link eingeblendet.

**Comment by ratnanil** [comment]
http://forschung.wieselundco.ch/erfolgskontrolle/  leitet jetzt automatisch auf https://erfolgskontrolle.wieselundco.ch/ weiter. 

Note to self: Auf metanet in /erfolgskontrolle/ folgendes index.html abgelegt:

```

<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting to https://erfolgskontrolle.wieselundco.ch/</title>
<meta http-equiv="refresh" content="0; URL=https://erfolgskontrolle.wieselundco.ch/">
<link rel="canonical" href="https://erfolgskontrolle.wieselundco.ch/">
```
